[package]
name = "rss2webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
rss = { version = "2.0.11", default-features = false, features = ["serde"] }
tokio = { version = "1.42.0", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
minreq = { version = "2.13.0", default-features = false, features = ["https"] }
